platformName: Android
#模拟器
platformVersion: 8.1.0
deviceName: 127.0.0.1:62001

#mx4真机
#platformVersion: 5.1
#udid: 750BBKL22GDN
#deviceName: MX4

appname: PalmSecret-release-vn1.0.0-vc1_200_svn28927_logtrue_abuserfalse.apk
noReset: False
unicodeKeyboard: True
resetKeyboard: True

appPackage: com.palm.test
appActivity: com.palmapp.master.launcher.LauncherActivity
ip: 127.0.0.1
port: 4723